### ISSUE TITLE
Update pip install command in README

### ISSUE THREAD

**Issue by martimpassos** [steven-murray/beet-summarize#8]
[`git://` is no longer supported](https://github.blog/2021-09-01-improving-git-protocol-security-github/)

**Comment by martimpassos** [comment]
I (think I) managed to install with `$ pip3 install git+https://github.com/steven-murray/beet-summarize.git`:
```
Successfully installed summarize-0.2.0
```
and have added both `summarize` to `plugins` and `/usr/local/lib/python3.9/site-packages` to `pluginpath` in my config, but `beet summarize` throws 
```
error: unknown command 'summarize'
```

**Comment by codeurimpulsif** [comment]
Same issue here.

**Comment by codeurimpulsif** [comment]
@martimpassos I found the issue:

- Uninstall the package
- Remove this line inside `beetsplug/__init__.py`:

```python
from .summarize import parse_stat, show_summary, summarize
```
- Install the package again

(In fact the `__init__` is not needed with this install method because the `summarize.py` file go inside the `/usr/local/lib/python3.9/dist-packages/beetsplug/` directory)

**Comment by steven-murray** [comment]
I've updated the README, thank you! Let me know if it gives you more trouble.
